name: Deploy

on:
  push:
    branches: [master]
    paths:
      - '**/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/nabous.dev
            git pull --ff-only
            docker build -t nabous-dev-builder -f Dockerfile.builder .
            docker run --rm -v /opt/nabous.dev/out:/app/out -v /opt/nabous.dev/.next/cache:/app/.next/cache nabous-dev-builder
            rm -rf /var/www/html/*
            cp -r /opt/nabous.dev/out/static/* /var/www/html/